const feelingsList = [
    { feeling: 'hopeless', icon: '😔' },
    { feeling: 'miserable', icon: '😞' },
    { feeling: 'deep', icon: '🤔' },
    { feeling: 'nervous', icon: '😬' },
    { feeling: 'wanted', icon: '😊' },
    { feeling: 'light', icon: '😇' },
    { feeling: 'secure', icon: '😌' },
    { feeling: 'whole', icon: '🙌' },
    { feeling: 'mad', icon: '😡' },
    { feeling: 'yucky', icon: '🤢' },
    { feeling: 'blue', icon: '💙' },
    { feeling: 'honoured', icon: '🙏' },
    { feeling: 'hung-over', icon: '🥴' },
    { feeling: 'insecure', icon: '😟' },
    { feeling: 'kind', icon: '🤗' },
    { feeling: 'dumb', icon: '🤪' },
    { feeling: 'important', icon: '💪' },
    { feeling: 'uncomfortable', icon: '😖' },
    { feeling: 'ready', icon: '🏃‍♂️' },
    { feeling: 'weak', icon: '😓' },
    { feeling: 'fine', icon: '😀' },
    { feeling: 'nice', icon: '😊' },
    { feeling: 'crappy', icon: '😕' },
    { feeling: 'different', icon: '🔄' },
    { feeling: 'awkward', icon: '😳' },
    { feeling: 'asleep', icon: '😴' },
    { feeling: 'well', icon: '👍' },
    { feeling: 'better', icon: '🆗' },
    { feeling: 'free', icon: '🆓' },
    { feeling: 'lost', icon: '🧐' },
    { feeling: 'ashamed', icon: '😳' },
    { feeling: 'normal', icon: '😐' },
    { feeling: 'stupid', icon: '🤦‍♂️' },
    { feeling: 'comfortable', icon: '😌' },
    { feeling: 'alive', icon: '🌟' },
    { feeling: 'human', icon: '🧑' },
    { feeling: 'spooky', icon: '👻' },
    { feeling: 'terrible', icon: '😩' },
    { feeling: 'warm', icon: '☀️' },
    { feeling: 'sarcastic', icon: '😏' },
    { feeling: 'strong', icon: '💪' },
    { feeling: 'special', icon: '🌟' },
    { feeling: 'jolly', icon: '😄' },
    { feeling: 'low', icon: '😞' },
    { feeling: 'broken', icon: '💔' },
    { feeling: 'amazing', icon: '😲' },
    { feeling: 'lonely', icon: '😔' },
    { feeling: 'concerned', icon: '😟' },
    { feeling: 'depressed', icon: '😔' },
    { feeling: 'curious', icon: '🤔' },
    { feeling: 'welcome', icon: '🤗' },
    { feeling: 'beautiful', icon: '😍' },
    { feeling: 'irritated', icon: '😠' }
  ];

  export default feelingsList;